# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CCD Antennas from UR5MED
email: ur5med73@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ur5med.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  ur5med

# Build settings
markdown: kramdown
